### ISSUE TITLE
name the mascot

### ISSUE THREAD

**Issue by JaegerwaldDev** [Nexulien/Nexulien#11]
### Content

![jae boykisser](https://github.com/user-attachments/assets/c4ef0c70-a997-4ff6-afb1-ed318dbcb616)

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by TheZoidMaster** [comment]
this is not an issue

**Comment by JaegerwaldDev** [comment]
nuh uh

**Comment by JaegerwaldDev** [comment]
you should ask goobert

**Comment by JaegerwaldDev** [comment]
im asking goobert again

**Comment by TheZoidMaster** [comment]
i forgot to close this earlier
